---

- name: Run script to find IP
  local_action: command ../roles/dynamic_prox_inventory/files/ipQueryCmdLine.py -n {{ node_name }} -v {{ vm_id }}
  register: ip_address

- name: Add host(s) to inventory
  add_host:
    name: '{{ vm_name }}'
    groups: new_hosts
    ansible_host: "{{ ip_address.stdout_lines[0] }}"

- name: Print output
  debug:
    msg: "{{ ip_address.stdout_lines[0] }}"