---

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  become: true
  vars:
    ansible_become_password: "{{ password }}"
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  become: true
  vars:
    ansible_become_password: "{{ password }}"
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'