---

# Gather hostname and uptime
- name: Get hostname
  command: /bin/hostname
  changed_when: False
  register: hostname
- name: Get uptime
  shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
  changed_when: False
  register: uptime
- name: Print output
  debug: var = {{ item }}
  with_items:
    - hostname.stdout
    - uptime.stdout