---

- name: Update cache
  become: true
  apt: update_cache=yes

- name: Install prereqs
  become: true
  apt:
    name: '{{ docker_apt_list }}'

- name: Add Docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker GPG key
  become: true
  shell: '{{ item }}'
  with_items:
    - curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -
    - apt-key fingerprint 0EBFCD88
  args:
    warn: false
  when: add_repository_key is failed

- name: Add Docker repo
  apt_repository:
    repo: >
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_lsb.id|lower }}
      {{ ansible_lsb.codename|lower }} stable
    mode: 664
    update_cache: yes
    state: present

- name: Update cache
  become: true
  apt: update_cache=yes

- name: Install docker
  become: true
  apt:
    name: 'docker-ce'

- name: Install docker-compose
  become: true
  pip:
    name: ['docker-compose']