---

- import_tasks: 00-update.yml
  when: ansible_os_family == "Debian"
- import_tasks: 01-baseline.yml
  when: ansible_os_family == "Debian"
- import_tasks: 02-docker.yml
  when: ansible_os_family == "Debian"